import Head from "next/head";



type PropsType = { title?: string }

export const MetaHead = ({ title }: PropsType) => (
    <Head>
        <title>{`One Social ${title? ` - ${title}` : ''}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
) 
